### ISSUE TITLE
SSL on justdeleteme.xyz

### ISSUE THREAD

**Issue by MikeRogers0** [jdm-contrib/jdm#158] opened 2017-12-06 21:17 UTC
I just noticed https://justdeleteme.xyz/ doesn't have an SSL certificate. Any way we could get one setup?

**Comment by Nightfirecat** [comment] 2017-12-06 21:52
Actually, it does have an SSL certificate, but as justdeleteme.xyz is serviced by GitHub Pages, the certificate is valid only for `*.github.com` and `*.github.io`; per isaacs/github#156, GitHub Pages being served on custom domains currently cannot support HTTPS.

That said, we could possibly [utilize a CloudFlare-based workaround for this](https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b).

**Comment by PyroSamurai** [comment] 2017-12-07 01:03
Assuming we decide to use the work around, this would definitely be a considered a "because we can" feature. There really isn't a functional need for SSL for this site, since we don't handle user data. Also it must still be able to support regular http. Regardless, @neeklamy would be in charge of making these changes.

Every time this topic comes up, I can't help but ask the question,"Why?"

**Comment by MikeRogers0** [comment] 2017-12-07 11:18
[HTTPS](https://webmasters.googleblog.com/2014/08/https-as-ranking-signal.html) is a ranking signal, plus if we're using CloudFlare it should make the site a bit faster via [HTTP/2](https://www.cloudflare.com/website-optimization/http2/).

**Comment by Nightfirecat** [comment] 2017-12-07 17:45
A better question, really, is why not?

Some reading from a quick search of "Why use HTTPS?":

* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
* https://https.cio.gov/everything/
* https://stackoverflow.com/questions/2746047/why-not-use-https-for-everything

Personally, I don't feel there's any reason not to implement it if we can.

**Comment by PyroSamurai** [comment] 2017-12-07 21:39
The useless advantages most articles state: SEO benefits and "everyone else is doing it"

What Mike said about performance was worth considering so I did some research.
What I found out is browsers were unwilling to implement HTTP/2 unencrypted despite the web standard not requiring encryption so the speed benefits are only available to encrypted site (wth).

Anyways, I confirmed there is an actual performance difference with this site: [httpvshttps](http://www.httpvshttps.com/)
You'll notice the little note at the bottom that states we lose the security benefits by using Cloudflare.

So the only benefits we gain is the speed and giving a false sense of security. The speed improvement alone is good enough for me though. I was unaware that the browsers had snub the http protocol in implementing http/2 (might as well call it https/2) :(

I'll talk to @neeklamy about getting it set up but it probably won't happen until after the holidays are over, both for him and myself. Family before work. Hopefully you can understand that and be patient.

**Comment by Nightfirecat** [comment] 2018-02-22 20:56
So actually, it looks like there's a fair amount of buzz lately on that issue I mentioned in my first comment--apparently GitHub is (slowly, in batches?) generating certificates for websites hosted on GitHub Pages using custom domains. Based on that, we should actually be able to sit tight and use the cert they will generate once they get around to it. :smile:

**Comment by tupaschoal** [comment] 2018-02-23 11:35
Hahahah great!

**Comment by PyroSamurai** [comment] 2018-02-23 17:01
sounds good. Nothing easier than waiting.

**Comment by Nightfirecat** [comment] 2018-05-02 23:32
:tada: https://justdeleteme.xyz

It is not yet the default as I want to wait a few hours to let DNS propagate, but I will close this issue once that's done.

**Comment by Nightfirecat** [comment] 2018-05-03 03:48
HTTPS is now enforced, and this ticket is resolved!

```
$ curl --silent --head http://justdeleteme.xyz | grep 'HTTP/[0-9]'
HTTP/1.1 301 Moved Permanently

$ curl --silent --head https://justdeleteme.xyz | grep 'HTTP/[0-9]'
HTTP/2 200
```

**Closed by Nightfirecat** 2018-05-03 03:48 UTC
